apiVersion: v1
kind: Service
metadata:
  name: dreba-db
spec:
  ports:
  - name: dreba-db
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: dreba-db
---
apiVersion: v1
kind: Service
metadata:
  name: dreba
spec:
  ports:
  - name: dreba
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dreba
